name: CI + SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # ---------------------------
      # TESTES + COVERAGE POR PROJETO
      # ---------------------------

      - name: Test UseCases
        run: |
          dotnet test tests/UseCases.Test/UseCases.Test.csproj `
            --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=opencover `
            /p:CoverletOutput=coverage/

      - name: Test Validators
        run: |
          dotnet test tests/Validators.Test/Validators.Test.csproj `
            --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=opencover `
            /p:CoverletOutput=coverage/

      - name: Test WebApi
        run: |
          dotnet test tests/WebApi.Test/WebApi.Test.csproj `
            --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=opencover `
            /p:CoverletOutput=coverage/

      # ---------------------------
      # SONARCLOUD
      # ---------------------------

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=thiagonogsl
            -Dsonar.organization=Thiagonogsl
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.cs.opencover.reportsPaths=tests/**/coverage/coverage.opencover.xml
            -Dsonar.exclusions=**/Migrations/**,**/Program.cs

